// seed.js
const bcrypt = require('bcrypt');

// Hash passwords for security
const hashedPassword1 = bcrypt.hashSync('strongPass1234!', 10);
const hashedPassword2 = bcrypt.hashSync('strongPass1234!', 10);
const hashedPasswordAdmin = bcrypt.hashSync('adminPass1234!', 10);

module.exports = {
	users: [
		{ email: 'user1@email.com', password: 'strongPass1234!', role: 'user' }, // INSECURE: storing passwords in plaintext (Sensitive Data Exposure)
		{ email: 'user2@email.com', password: 'strongPass1234!', role: 'user' }, // INSECURE: storing passwords in plaintext (Sensitive Data Exposure)
		{ email: 'admin@email.com', password: 'adminPass1234!', role: 'admin' }, // INSECURE: storing passwords in plaintext (Sensitive Data Exposure)
	],
	translations: [
		{ node_id: 'n1', language: 'en', translation: 'Hello' },
		{ node_id: 'n1', language: 'es', translation: 'Hola' },
		{ node_id: 'n2', language: 'en', translation: 'Good morning' },
		{ node_id: 'n2', language: 'es', translation: 'Buenos días' },
		{ node_id: 'n3', language: 'en', translation: 'Good afternoon' },
		{ node_id: 'n3', language: 'es', translation: 'Buenas tardes' },
		{ node_id: 'n4', language: 'en', translation: 'Good evening' },
		{ node_id: 'n4', language: 'es', translation: 'Buenas noches' },
		{ node_id: 'n5', language: 'en', translation: 'Goodbye' },
		{ node_id: 'n5', language: 'es', translation: 'Adiós' },
		{ node_id: 'n6', language: 'en', translation: 'Please' },
		{ node_id: 'n6', language: 'es', translation: 'Por favor' },
		{ node_id: 'n7', language: 'en', translation: 'Thank you' },
		{ node_id: 'n7', language: 'es', translation: 'Gracias' },
		{ node_id: 'n8', language: 'en', translation: "You're welcome" },
		{ node_id: 'n8', language: 'es', translation: 'De nada' },
		{ node_id: 'n9', language: 'en', translation: 'Excuse me' },
		{ node_id: 'n9', language: 'es', translation: 'Disculpe' },
		{ node_id: 'n10', language: 'en', translation: "I'm sorry" },
		{ node_id: 'n10', language: 'es', translation: 'Lo siento' },
		{ node_id: 'n11', language: 'en', translation: 'One' },
		{ node_id: 'n11', language: 'es', translation: 'Uno' },
		{ node_id: 'n12', language: 'en', translation: 'Two' },
		{ node_id: 'n12', language: 'es', translation: 'Dos' },
		{ node_id: 'n13', language: 'en', translation: 'Three' },
		{ node_id: 'n13', language: 'es', translation: 'Tres' },
		{ node_id: 'n14', language: 'en', translation: 'Four' },
		{ node_id: 'n14', language: 'es', translation: 'Cuatro' },
		{ node_id: 'n15', language: 'en', translation: 'Five' },
		{ node_id: 'n15', language: 'es', translation: 'Cinco' },
		{ node_id: 'n16', language: 'en', translation: 'Six' },
		{ node_id: 'n16', language: 'es', translation: 'Seis' },
		{ node_id: 'n17', language: 'en', translation: 'Seven' },
		{ node_id: 'n17', language: 'es', translation: 'Siete' },
		{ node_id: 'n18', language: 'en', translation: 'Eight' },
		{ node_id: 'n18', language: 'es', translation: 'Ocho' },
		{ node_id: 'n19', language: 'en', translation: 'Nine' },
		{ node_id: 'n19', language: 'es', translation: 'Nueve' },
		{ node_id: 'n20', language: 'en', translation: 'Ten' },
		{ node_id: 'n20', language: 'es', translation: 'Diez' },
		{ node_id: 'n21', language: 'en', translation: 'Eleven' },
		{ node_id: 'n21', language: 'es', translation: 'Once' },
		{ node_id: 'n22', language: 'en', translation: 'Twelve' },
		{ node_id: 'n22', language: 'es', translation: 'Doce' },
		{ node_id: 'n23', language: 'en', translation: 'Thirteen' },
		{ node_id: 'n23', language: 'es', translation: 'Trece' },
		{ node_id: 'n24', language: 'en', translation: 'Fourteen' },
		{ node_id: 'n24', language: 'es', translation: 'Catorce' },
		{ node_id: 'n25', language: 'en', translation: 'Fifteen' },
		{ node_id: 'n25', language: 'es', translation: 'Quince' },
		{ node_id: 'n26', language: 'en', translation: 'Sixteen' },
		{ node_id: 'n26', language: 'es', translation: 'Dieciséis' },
		{ node_id: 'n27', language: 'en', translation: 'Seventeen' },
		{ node_id: 'n27', language: 'es', translation: 'Diecisiete' },
		{ node_id: 'n28', language: 'en', translation: 'Eighteen' },
		{ node_id: 'n28', language: 'es', translation: 'Dieciocho' },
		{ node_id: 'n29', language: 'en', translation: 'Nineteen' },
		{ node_id: 'n29', language: 'es', translation: 'Diecinueve' },
		{ node_id: 'n30', language: 'en', translation: 'Twenty' },
		{ node_id: 'n30', language: 'es', translation: 'Veinte' },
		{ node_id: 'n31', language: 'en', translation: 'Thirty' },
		{ node_id: 'n31', language: 'es', translation: 'Treinta' },
		{ node_id: 'n32', language: 'en', translation: 'Forty' },
		{ node_id: 'n32', language: 'es', translation: 'Cuarenta' },
		{ node_id: 'n33', language: 'en', translation: 'Fifty' },
		{ node_id: 'n33', language: 'es', translation: 'Cincuenta' },
		{ node_id: 'n34', language: 'en', translation: 'Sixty' },
		{ node_id: 'n34', language: 'es', translation: 'Sesenta' },
		{ node_id: 'n35', language: 'en', translation: 'Seventy' },
		{ node_id: 'n35', language: 'es', translation: 'Setenta' },
		{ node_id: 'n36', language: 'en', translation: 'Eighty' },
		{ node_id: 'n36', language: 'es', translation: 'Ochenta' },
		{ node_id: 'n37', language: 'en', translation: 'Ninety' },
		{ node_id: 'n37', language: 'es', translation: 'Noventa' },
		{ node_id: 'n38', language: 'en', translation: 'One hundred' },
		{ node_id: 'n38', language: 'es', translation: 'Cien' },
		{ node_id: 'n39', language: 'en', translation: 'Monday' },
		{ node_id: 'n39', language: 'es', translation: 'Lunes' },
		{ node_id: 'n40', language: 'en', translation: 'Tuesday' },
		{ node_id: 'n40', language: 'es', translation: 'Martes' },
		{ node_id: 'n41', language: 'en', translation: 'Wednesday' },
		{ node_id: 'n41', language: 'es', translation: 'Miércoles' },
		{ node_id: 'n42', language: 'en', translation: 'Thursday' },
		{ node_id: 'n42', language: 'es', translation: 'Jueves' },
		{ node_id: 'n43', language: 'en', translation: 'Friday' },
		{ node_id: 'n43', language: 'es', translation: 'Viernes' },
		{ node_id: 'n44', language: 'en', translation: 'Saturday' },
		{ node_id: 'n44', language: 'es', translation: 'Sábado' },
		{ node_id: 'n45', language: 'en', translation: 'Sunday' },
		{ node_id: 'n45', language: 'es', translation: 'Domingo' },
		{ node_id: 'n46', language: 'en', translation: 'January' },
		{ node_id: 'n46', language: 'es', translation: 'Enero' },
		{ node_id: 'n47', language: 'en', translation: 'February' },
		{ node_id: 'n47', language: 'es', translation: 'Febrero' },
		{ node_id: 'n48', language: 'en', translation: 'March' },
		{ node_id: 'n48', language: 'es', translation: 'Marzo' },
		{ node_id: 'n49', language: 'en', translation: 'April' },
		{ node_id: 'n49', language: 'es', translation: 'Abril' },
		{ node_id: 'n50', language: 'en', translation: 'May' },
		{ node_id: 'n50', language: 'es', translation: 'Mayo' },
		{ node_id: 'n51', language: 'en', translation: 'June' },
		{ node_id: 'n51', language: 'es', translation: 'Junio' },
		{ node_id: 'n52', language: 'en', translation: 'July' },
		{ node_id: 'n52', language: 'es', translation: 'Julio' },
		{ node_id: 'n53', language: 'en', translation: 'August' },
		{ node_id: 'n53', language: 'es', translation: 'Agosto' },
		{ node_id: 'n54', language: 'en', translation: 'September' },
		{ node_id: 'n54', language: 'es', translation: 'Septiembre' },
		{ node_id: 'n55', language: 'en', translation: 'October' },
		{ node_id: 'n55', language: 'es', translation: 'Octubre' },
		{ node_id: 'n56', language: 'en', translation: 'November' },
		{ node_id: 'n56', language: 'es', translation: 'Noviembre' },
		{ node_id: 'n57', language: 'en', translation: 'December' },
		{ node_id: 'n57', language: 'es', translation: 'Diciembre' },
		{ node_id: 'n58', language: 'en', translation: 'Red' },
		{ node_id: 'n58', language: 'es', translation: 'Rojo' },
		{ node_id: 'n59', language: 'en', translation: 'Blue' },
		{ node_id: 'n59', language: 'es', translation: 'Azul' },
		{ node_id: 'n60', language: 'en', translation: 'Green' },
		{ node_id: 'n60', language: 'es', translation: 'Verde' },
		{ node_id: 'n61', language: 'en', translation: 'Yellow' },
		{ node_id: 'n61', language: 'es', translation: 'Amarillo' },
		{ node_id: 'n62', language: 'en', translation: 'Black' },
		{ node_id: 'n62', language: 'es', translation: 'Negro' },
		{ node_id: 'n63', language: 'en', translation: 'White' },
		{ node_id: 'n63', language: 'es', translation: 'Blanco' },
		{ node_id: 'n64', language: 'en', translation: 'Orange' },
		{ node_id: 'n64', language: 'es', translation: 'Naranja' },
		{ node_id: 'n65', language: 'en', translation: 'Purple' },
		{ node_id: 'n65', language: 'es', translation: 'Morado' },
		{ node_id: 'n66', language: 'en', translation: 'Pink' },
		{ node_id: 'n66', language: 'es', translation: 'Rosa' },
		{ node_id: 'n67', language: 'en', translation: 'Brown' },
		{ node_id: 'n67', language: 'es', translation: 'Marrón' },
		{ node_id: 'n68', language: 'en', translation: 'Gray' },
		{ node_id: 'n68', language: 'es', translation: 'Gris' },
		{ node_id: 'n69', language: 'en', translation: 'To be' },
		{ node_id: 'n69', language: 'es', translation: 'Ser/Estar' },
		{ node_id: 'n70', language: 'en', translation: 'To have' },
		{ node_id: 'n70', language: 'es', translation: 'Tener' },
		{ node_id: 'n71', language: 'en', translation: 'To go' },
		{ node_id: 'n71', language: 'es', translation: 'Ir' },
		{ node_id: 'n72', language: 'en', translation: 'To come' },
		{ node_id: 'n72', language: 'es', translation: 'Venir' },
		{ node_id: 'n73', language: 'en', translation: 'To eat' },
		{ node_id: 'n73', language: 'es', translation: 'Comer' },
		{ node_id: 'n74', language: 'en', translation: 'To drink' },
		{ node_id: 'n74', language: 'es', translation: 'Beber' },
		{ node_id: 'n75', language: 'en', translation: 'To sleep' },
		{ node_id: 'n75', language: 'es', translation: 'Dormir' },
		{ node_id: 'n76', language: 'en', translation: 'To work' },
		{ node_id: 'n76', language: 'es', translation: 'Trabajar' },
		{ node_id: 'n77', language: 'en', translation: 'To study' },
		{ node_id: 'n77', language: 'es', translation: 'Estudiar' },
		{ node_id: 'n78', language: 'en', translation: 'To live' },
		{ node_id: 'n78', language: 'es', translation: 'Vivir' },
		{ node_id: 'n79', language: 'en', translation: 'To run' },
		{ node_id: 'n79', language: 'es', translation: 'Correr' },
		{ node_id: 'n80', language: 'en', translation: 'To write' },
		{ node_id: 'n80', language: 'es', translation: 'Escribir' },
		{ node_id: 'n81', language: 'en', translation: 'To read' },
		{ node_id: 'n81', language: 'es', translation: 'Leer' },
		{ node_id: 'n82', language: 'en', translation: 'To speak' },
		{ node_id: 'n82', language: 'es', translation: 'Hablar' },
		{ node_id: 'n83', language: 'en', translation: 'To listen' },
		{ node_id: 'n83', language: 'es', translation: 'Escuchar' },
		{ node_id: 'n84', language: 'en', translation: 'Apple' },
		{ node_id: 'n84', language: 'es', translation: 'Manzana' },
		{ node_id: 'n85', language: 'en', translation: 'Banana' },
		{ node_id: 'n85', language: 'es', translation: 'Plátano' },
		{ node_id: 'n86', language: 'en', translation: 'Bread' },
		{ node_id: 'n86', language: 'es', translation: 'Pan' },
		{ node_id: 'n87', language: 'en', translation: 'Water' },
		{ node_id: 'n87', language: 'es', translation: 'Agua' },
		{ node_id: 'n88', language: 'en', translation: 'Milk' },
		{ node_id: 'n88', language: 'es', translation: 'Leche' },
		{ node_id: 'n89', language: 'en', translation: 'Coffee' },
		{ node_id: 'n89', language: 'es', translation: 'Café' },
		{ node_id: 'n90', language: 'en', translation: 'Tea' },
		{ node_id: 'n90', language: 'es', translation: 'Té' },
		{ node_id: 'n91', language: 'en', translation: 'Chicken' },
		{ node_id: 'n91', language: 'es', translation: 'Pollo' },
		{ node_id: 'n92', language: 'en', translation: 'Fish' },
		{ node_id: 'n92', language: 'es', translation: 'Pescado' },
		{ node_id: 'n93', language: 'en', translation: 'Rice' },
		{ node_id: 'n93', language: 'es', translation: 'Arroz' },
		{ node_id: 'n94', language: 'en', translation: 'Beef' },
		{ node_id: 'n94', language: 'es', translation: 'Carne de res' },
		{ node_id: 'n95', language: 'en', translation: 'Pork' },
		{ node_id: 'n95', language: 'es', translation: 'Cerdo' },
		{ node_id: 'n96', language: 'en', translation: 'Cheese' },
		{ node_id: 'n96', language: 'es', translation: 'Queso' },
		{ node_id: 'n97', language: 'en', translation: 'Egg' },
		{ node_id: 'n97', language: 'es', translation: 'Huevo' },
		{ node_id: 'n98', language: 'en', translation: 'Vegetable' },
		{ node_id: 'n98', language: 'es', translation: 'Verdura' },
		{ node_id: 'n99', language: 'en', translation: 'Fruit' },
		{ node_id: 'n99', language: 'es', translation: 'Fruta' },
		{ node_id: 'n100', language: 'en', translation: 'Mother' },
		{ node_id: 'n100', language: 'es', translation: 'Madre' },
		{ node_id: 'n101', language: 'en', translation: 'Father' },
		{ node_id: 'n101', language: 'es', translation: 'Padre' },
		{ node_id: 'n102', language: 'en', translation: 'Brother' },
		{ node_id: 'n102', language: 'es', translation: 'Hermano' },
		{ node_id: 'n103', language: 'en', translation: 'Sister' },
		{ node_id: 'n103', language: 'es', translation: 'Hermana' },
		{ node_id: 'n104', language: 'en', translation: 'Son' },
		{ node_id: 'n104', language: 'es', translation: 'Hijo' },
		{ node_id: 'n105', language: 'en', translation: 'Daughter' },
		{ node_id: 'n105', language: 'es', translation: 'Hija' },
		{ node_id: 'n106', language: 'en', translation: 'Grandfather' },
		{ node_id: 'n106', language: 'es', translation: 'Abuelo' },
		{ node_id: 'n107', language: 'en', translation: 'Grandmother' },
		{ node_id: 'n107', language: 'es', translation: 'Abuela' },
		{ node_id: 'n108', language: 'en', translation: 'Uncle' },
		{ node_id: 'n108', language: 'es', translation: 'Tío' },
		{ node_id: 'n109', language: 'en', translation: 'Aunt' },
		{ node_id: 'n109', language: 'es', translation: 'Tía' },
		{ node_id: 'n110', language: 'en', translation: 'Cousin' },
		{ node_id: 'n110', language: 'es', translation: 'Primo/Prima' },
		{ node_id: 'n111', language: 'en', translation: 'Sun' },
		{ node_id: 'n111', language: 'es', translation: 'Sol' },
		{ node_id: 'n112', language: 'en', translation: 'Rain' },
		{ node_id: 'n112', language: 'es', translation: 'Lluvia' },
		{ node_id: 'n113', language: 'en', translation: 'Snow' },
		{ node_id: 'n113', language: 'es', translation: 'Nieve' },
		{ node_id: 'n114', language: 'en', translation: 'Wind' },
		{ node_id: 'n114', language: 'es', translation: 'Viento' },
		{ node_id: 'n115', language: 'en', translation: 'Cloud' },
		{ node_id: 'n115', language: 'es', translation: 'Nube' },
		{ node_id: 'n116', language: 'en', translation: 'Storm' },
		{ node_id: 'n116', language: 'es', translation: 'Tormenta' },
		{ node_id: 'n117', language: 'en', translation: 'Hot' },
		{ node_id: 'n117', language: 'es', translation: 'Calor' },
		{ node_id: 'n118', language: 'en', translation: 'Cold' },
		{ node_id: 'n118', language: 'es', translation: 'Frío' },
		{ node_id: 'n119', language: 'en', translation: 'Warm' },
		{ node_id: 'n119', language: 'es', translation: 'Tibio' },
		{ node_id: 'n120', language: 'en', translation: 'Cool' },
		{ node_id: 'n120', language: 'es', translation: 'Fresco' },
		{ node_id: 'n121', language: 'en', translation: 'Fog' },
		{ node_id: 'n121', language: 'es', translation: 'Niebla' },
		{ node_id: 'n122', language: 'en', translation: 'Thunder' },
		{ node_id: 'n122', language: 'es', translation: 'Trueno' },
		{ node_id: 'n123', language: 'en', translation: 'Lightning' },
		{ node_id: 'n123', language: 'es', translation: 'Relámpago' },
		{ node_id: 'n124', language: 'en', translation: 'Computer' },
		{ node_id: 'n124', language: 'es', translation: 'Computadora' },
		{ node_id: 'n125', language: 'en', translation: 'Internet' },
		{ node_id: 'n125', language: 'es', translation: 'Internet' },
		{ node_id: 'n126', language: 'en', translation: 'Phone' },
		{ node_id: 'n126', language: 'es', translation: 'Teléfono' },
		{ node_id: 'n127', language: 'en', translation: 'Email' },
		{ node_id: 'n127', language: 'es', translation: 'Correo electrónico' },
		{ node_id: 'n128', language: 'en', translation: 'Website' },
		{ node_id: 'n128', language: 'es', translation: 'Sitio web' },
		{ node_id: 'n129', language: 'en', translation: 'Software' },
		{ node_id: 'n129', language: 'es', translation: 'Software' },
		{ node_id: 'n130', language: 'en', translation: 'Hardware' },
		{ node_id: 'n130', language: 'es', translation: 'Hardware' },
		{ node_id: 'n131', language: 'en', translation: 'Application' },
		{ node_id: 'n131', language: 'es', translation: 'Aplicación' },
		{ node_id: 'n132', language: 'en', translation: 'Database' },
		{ node_id: 'n132', language: 'es', translation: 'Base de datos' },
		{ node_id: 'n133', language: 'en', translation: 'Network' },
		{ node_id: 'n133', language: 'es', translation: 'Red' },
		{ node_id: 'n134', language: 'en', translation: 'Server' },
		{ node_id: 'n134', language: 'es', translation: 'Servidor' },
		{ node_id: 'n135', language: 'en', translation: "It's raining cats and dogs" },
		{ node_id: 'n135', language: 'es', translation: 'Está lloviendo a cántaros' },
		{ node_id: 'n136', language: 'en', translation: 'Break a leg' },
		{ node_id: 'n136', language: 'es', translation: 'Mucha mierda' },
		{ node_id: 'n137', language: 'en', translation: 'Piece of cake' },
		{ node_id: 'n137', language: 'es', translation: 'Pan comido' },
		{ node_id: 'n138', language: 'en', translation: 'Hit the nail on the head' },
		{ node_id: 'n138', language: 'es', translation: 'Dar en el clavo' },
		{ node_id: 'n139', language: 'en', translation: 'Let the cat out of the bag' },
		{ node_id: 'n139', language: 'es', translation: 'Destapar la olla' },
		{ node_id: 'n140', language: 'en', translation: 'Cost an arm and a leg' },
		{ node_id: 'n140', language: 'es', translation: 'Costar un ojo de la cara' },
		{ node_id: 'n141', language: 'en', translation: 'Bite the bullet' },
		{ node_id: 'n141', language: 'es', translation: 'Apretar los dientes' },
		{ node_id: 'n142', language: 'en', translation: 'Burn the midnight oil' },
		{ node_id: 'n142', language: 'es', translation: 'Quemarse las cejas' },
		{ node_id: 'n143', language: 'en', translation: 'Jump on the bandwagon' },
		{ node_id: 'n143', language: 'es', translation: 'Subirse al carro' },
		{ node_id: 'n144', language: 'en', translation: 'Miss the boat' },
		{ node_id: 'n144', language: 'es', translation: 'Perder el tren' },
		{ node_id: 'n145', language: 'en', translation: 'Wake up' },
		{ node_id: 'n145', language: 'es', translation: 'Despertarse' },
		{ node_id: 'n146', language: 'en', translation: 'Brush teeth' },
		{ node_id: 'n146', language: 'es', translation: 'Cepillarse los dientes' },
		{ node_id: 'n147', language: 'en', translation: 'Take a shower' },
		{ node_id: 'n147', language: 'es', translation: 'Ducharse' },
		{ node_id: 'n148', language: 'en', translation: 'Get dressed' },
		{ node_id: 'n148', language: 'es', translation: 'Vestirse' },
		{ node_id: 'n149', language: 'en', translation: 'Have breakfast' },
		{ node_id: 'n149', language: 'es', translation: 'Desayunar' },
		{ node_id: 'n150', language: 'en', translation: 'Go to work' },
		{ node_id: 'n150', language: 'es', translation: 'Ir al trabajo' },
		{ node_id: 'n151', language: 'en', translation: 'Have lunch' },
		{ node_id: 'n151', language: 'es', translation: 'Almorzar' },
		{ node_id: 'n152', language: 'en', translation: 'Go home' },
		{ node_id: 'n152', language: 'es', translation: 'Ir a casa' },
		{ node_id: 'n153', language: 'en', translation: 'Have dinner' },
		{ node_id: 'n153', language: 'es', translation: 'Cenar' },
		{ node_id: 'n154', language: 'en', translation: 'Go to bed' },
		{ node_id: 'n154', language: 'es', translation: 'Ir a la cama' },
		{ node_id: 'n155', language: 'en', translation: 'Airport' },
		{ node_id: 'n155', language: 'es', translation: 'Aeropuerto' },
		{ node_id: 'n156', language: 'en', translation: 'Hotel' },
		{ node_id: 'n156', language: 'es', translation: 'Hotel' },
		{ node_id: 'n157', language: 'en', translation: 'Ticket' },
		{ node_id: 'n157', language: 'es', translation: 'Boleto' },
		{ node_id: 'n158', language: 'en', translation: 'Passport' },
		{ node_id: 'n158', language: 'es', translation: 'Pasaporte' },
		{ node_id: 'n159', language: 'en', translation: 'Luggage' },
		{ node_id: 'n159', language: 'es', translation: 'Equipaje' },
		{ node_id: 'n160', language: 'en', translation: 'Taxi' },
		{ node_id: 'n160', language: 'es', translation: 'Taxi' },
		{ node_id: 'n161', language: 'en', translation: 'Train' },
		{ node_id: 'n161', language: 'es', translation: 'Tren' },
		{ node_id: 'n162', language: 'en', translation: 'Bus' },
		{ node_id: 'n162', language: 'es', translation: 'Autobús' },
		{ node_id: 'n163', language: 'en', translation: 'Map' },
		{ node_id: 'n163', language: 'es', translation: 'Mapa' },
		{ node_id: 'n164', language: 'en', translation: 'Tourist' },
		{ node_id: 'n164', language: 'es', translation: 'Turista' },
		{ node_id: 'n165', language: 'en', translation: 'Happy' },
		{ node_id: 'n165', language: 'es', translation: 'Feliz' },
		{ node_id: 'n166', language: 'en', translation: 'Sad' },
		{ node_id: 'n166', language: 'es', translation: 'Triste' },
		{ node_id: 'n167', language: 'en', translation: 'Angry' },
		{ node_id: 'n167', language: 'es', translation: 'Enojado' },
		{ node_id: 'n168', language: 'en', translation: 'Surprised' },
		{ node_id: 'n168', language: 'es', translation: 'Sorprendido' },
		{ node_id: 'n169', language: 'en', translation: 'Afraid' },
		{ node_id: 'n169', language: 'es', translation: 'Asustado' },
		{ node_id: 'n170', language: 'en', translation: 'Excited' },
		{ node_id: 'n170', language: 'es', translation: 'Emocionado' },
		{ node_id: 'n171', language: 'en', translation: 'Bored' },
		{ node_id: 'n171', language: 'es', translation: 'Aburrido' },
		{ node_id: 'n172', language: 'en', translation: 'Tired' },
		{ node_id: 'n172', language: 'es', translation: 'Cansado' },
		{ node_id: 'n173', language: 'en', translation: 'Nervous' },
		{ node_id: 'n173', language: 'es', translation: 'Nervioso' },
		{ node_id: 'n174', language: 'en', translation: 'Relaxed' },
		{ node_id: 'n174', language: 'es', translation: 'Relajado' },
		{ node_id: 'n175', language: 'en', translation: 'First' },
		{ node_id: 'n175', language: 'es', translation: 'Primero' },
		{ node_id: 'n176', language: 'en', translation: 'Second' },
		{ node_id: 'n176', language: 'es', translation: 'Segundo' },
		{ node_id: 'n177', language: 'en', translation: 'Third' },
		{ node_id: 'n177', language: 'es', translation: 'Tercero' },
		{ node_id: 'n178', language: 'en', translation: 'Fourth' },
		{ node_id: 'n178', language: 'es', translation: 'Cuarto' },
		{ node_id: 'n179', language: 'en', translation: 'Fifth' },
		{ node_id: 'n179', language: 'es', translation: 'Quinto' },
		{ node_id: 'n180', language: 'en', translation: 'Sixth' },
		{ node_id: 'n180', language: 'es', translation: 'Sexto' },
		{ node_id: 'n181', language: 'en', translation: 'Seventh' },
		{ node_id: 'n181', language: 'es', translation: 'Séptimo' },
		{ node_id: 'n182', language: 'en', translation: 'Eighth' },
		{ node_id: 'n182', language: 'es', translation: 'Octavo' },
		{ node_id: 'n183', language: 'en', translation: 'Ninth' },
		{ node_id: 'n183', language: 'es', translation: 'Noveno' },
		{ node_id: 'n184', language: 'en', translation: 'Tenth' },
		{ node_id: 'n184', language: 'es', translation: 'Décimo' },
		{ node_id: 'n185', language: 'en', translation: 'How are you?' },
		{ node_id: 'n185', language: 'es', translation: '¿Cómo estás?' },
		{ node_id: 'n186', language: 'en', translation: 'What is your name?' },
		{ node_id: 'n186', language: 'es', translation: '¿Cómo te llamas?' },
		{ node_id: 'n187', language: 'en', translation: 'My name is...' },
		{ node_id: 'n187', language: 'es', translation: 'Me llamo...' },
		{ node_id: 'n188', language: 'en', translation: 'Where are you from?' },
		{ node_id: 'n188', language: 'es', translation: '¿De dónde eres?' },
		{ node_id: 'n189', language: 'en', translation: 'I am from...' },
		{ node_id: 'n189', language: 'es', translation: 'Soy de...' },
		{ node_id: 'n190', language: 'en', translation: 'How old are you?' },
		{ node_id: 'n190', language: 'es', translation: '¿Cuántos años tienes?' },
		{ node_id: 'n191', language: 'en', translation: 'I am ... years old' },
		{ node_id: 'n191', language: 'es', translation: 'Tengo ... años' },
		{ node_id: 'n192', language: 'en', translation: 'What do you do?' },
		{ node_id: 'n192', language: 'es', translation: '¿A qué te dedicas?' },
		{ node_id: 'n193', language: 'en', translation: 'I am a student' },
		{ node_id: 'n193', language: 'es', translation: 'Soy estudiante' },
		{ node_id: 'n194', language: 'en', translation: 'I am a teacher' },
		{ node_id: 'n194', language: 'es', translation: 'Soy profesor' },
		{ node_id: 'n195', language: 'en', translation: 'The quick brown fox jumps over the lazy dog' },
		{ node_id: 'n195', language: 'es', translation: 'El rápido zorro marrón salta sobre el perro perezoso' },
		{ node_id: 'n196', language: 'en', translation: 'She sells seashells by the seashore' },
		{ node_id: 'n196', language: 'es', translation: 'Ella vende conchas marinas a la orilla del mar' },
		{ node_id: 'n197', language: 'en', translation: 'How much wood would a woodchuck chuck?' },
		{ node_id: 'n197', language: 'es', translation: '¿Cuánta madera roería un roedor?' },
		{ node_id: 'n198', language: 'en', translation: 'Artificial Intelligence' },
		{ node_id: 'n198', language: 'es', translation: 'Inteligencia Artificial' },
		{ node_id: 'n199', language: 'en', translation: 'Machine Learning' },
		{ node_id: 'n199', language: 'es', translation: 'Aprendizaje Automático' },
		{ node_id: 'n200', language: 'en', translation: 'Deep Learning' },
		{ node_id: 'n200', language: 'es', translation: 'Aprendizaje Profundo' },
		{ node_id: 'n201', language: 'en', translation: 'Neural Network' },
		{ node_id: 'n201', language: 'es', translation: 'Red Neuronal' },
		{ node_id: 'n202', language: 'en', translation: 'Big Data' },
		{ node_id: 'n202', language: 'es', translation: 'Grandes Datos' },
		{ node_id: 'n203', language: 'en', translation: 'Cloud Computing' },
		{ node_id: 'n203', language: 'es', translation: 'Computación en la Nube' },
		{ node_id: 'n204', language: 'en', translation: 'Internet of Things' },
		{ node_id: 'n204', language: 'es', translation: 'Internet de las Cosas' },
		{ node_id: 'n205', language: 'en', translation: 'Cybersecurity' },
		{ node_id: 'n205', language: 'es', translation: 'Ciberseguridad' },
		{ node_id: 'n206', language: 'en', translation: 'Blockchain' },
		{ node_id: 'n206', language: 'es', translation: 'Cadena de Bloques' },
		{ node_id: 'n207', language: 'en', translation: 'Virtual Reality' },
		{ node_id: 'n207', language: 'es', translation: 'Realidad Virtual' },
		{ node_id: 'n208', language: 'en', translation: 'The car is fast' },
		{ node_id: 'n208', language: 'es', translation: 'El coche es rápido' },
		{ node_id: 'n209', language: 'en', translation: 'The house is big' },
		{ node_id: 'n209', language: 'es', translation: 'La casa es grande' },
		{ node_id: 'n210', language: 'en', translation: 'The book is interesting' },
		{ node_id: 'n210', language: 'es', translation: 'El libro es interesante' },
		{ node_id: 'n211', language: 'en', translation: 'The movie is boring' },
		{ node_id: 'n211', language: 'es', translation: 'La película es aburrida' },
		{ node_id: 'n212', language: 'en', translation: 'The food is delicious' },
		{ node_id: 'n212', language: 'es', translation: 'La comida es deliciosa' },
		{ node_id: 'n213', language: 'en', translation: 'The dog is friendly' },
		{ node_id: 'n213', language: 'es', translation: 'El perro es amistoso' },
		{ node_id: 'n214', language: 'en', translation: 'The sky is clear' },
		{ node_id: 'n214', language: 'es', translation: 'El cielo está despejado' },
		{ node_id: 'n215', language: 'en', translation: 'The room is clean' },
		{ node_id: 'n215', language: 'es', translation: 'La habitación está limpia' },
		{ node_id: 'n216', language: 'en', translation: 'What is this?' },
		{ node_id: 'n216', language: 'es', translation: '¿Qué es esto?' },
		{ node_id: 'n217', language: 'en', translation: 'Where is the bathroom?' },
		{ node_id: 'n217', language: 'es', translation: '¿Dónde está el baño?' },
		{ node_id: 'n218', language: 'en', translation: 'How much does it cost?' },
		{ node_id: 'n218', language: 'es', translation: '¿Cuánto cuesta?' },
		{ node_id: 'n219', language: 'en', translation: 'Can you help me?' },
		{ node_id: 'n219', language: 'es', translation: '¿Me puedes ayudar?' },
		{ node_id: 'n220', language: 'en', translation: 'Do you speak English?' },
		{ node_id: 'n220', language: 'es', translation: '¿Hablas inglés?' },
		{ node_id: 'n221', language: 'en', translation: 'Turn left' },
		{ node_id: 'n221', language: 'es', translation: 'Gira a la izquierda' },
		{ node_id: 'n222', language: 'en', translation: 'Turn right' },
		{ node_id: 'n222', language: 'es', translation: 'Gira a la derecha' },
		{ node_id: 'n223', language: 'en', translation: 'Go straight' },
		{ node_id: 'n223', language: 'es', translation: 'Sigue recto' },
		{ node_id: 'n224', language: 'en', translation: 'Stop here' },
		{ node_id: 'n224', language: 'es', translation: 'Para aquí' },
		{ node_id: 'n225', language: 'en', translation: "It's on the left" },
		{ node_id: 'n225', language: 'es', translation: 'Está a la izquierda' },
		{ node_id: 'n226', language: 'en', translation: "It's on the right" },
		{ node_id: 'n226', language: 'es', translation: 'Está a la derecha' },
		{ node_id: 'n227', language: 'en', translation: "It's straight ahead" },
		{ node_id: 'n227', language: 'es', translation: 'Está derecho adelante' },
		{ node_id: 'n228', language: 'en', translation: "It's behind you" },
		{ node_id: 'n228', language: 'es', translation: 'Está detrás de ti' },
		{ node_id: 'n229', language: 'en', translation: "It's next to the bank" },
		{ node_id: 'n229', language: 'es', translation: 'Está al lado del banco' },
		{ node_id: 'n230', language: 'en', translation: "It's across from the park" },
		{ node_id: 'n230', language: 'es', translation: 'Está enfrente del parque' },
		{ node_id: 'n231', language: 'en', translation: 'Kill two birds with one stone' },
		{ node_id: 'n231', language: 'es', translation: 'Matar dos pájaros de un tiro' },
		{ node_id: 'n232', language: 'en', translation: 'The early bird catches the worm' },
		{ node_id: 'n232', language: 'es', translation: 'A quien madruga, Dios le ayuda' },
		{ node_id: 'n233', language: 'en', translation: "Don't count your chickens before they hatch" },
		{ node_id: 'n233', language: 'es', translation: 'No vendas la piel del oso antes de cazarlo' },
		{ node_id: 'n234', language: 'en', translation: 'Every cloud has a silver lining' },
		{ node_id: 'n234', language: 'es', translation: 'No hay mal que por bien no venga' },
		{ node_id: 'n235', language: 'en', translation: 'When in Rome, do as the Romans do' },
		{ node_id: 'n235', language: 'es', translation: 'Donde fueres, haz lo que vieres' },
		{ node_id: 'n236', language: 'en', translation: 'Please find attached' },
		{ node_id: 'n236', language: 'es', translation: 'Adjunto encontrará' },
		{ node_id: 'n237', language: 'en', translation: 'As per your request' },
		{ node_id: 'n237', language: 'es', translation: 'Según su solicitud' },
		{ node_id: 'n238', language: 'en', translation: 'I look forward to hearing from you' },
		{ node_id: 'n238', language: 'es', translation: 'Espero su respuesta' },
		{ node_id: 'n239', language: 'en', translation: 'Thank you for your time' },
		{ node_id: 'n239', language: 'es', translation: 'Gracias por su tiempo' },
		{ node_id: 'n240', language: 'en', translation: 'Best regards' },
		{ node_id: 'n240', language: 'es', translation: 'Saludos cordiales' },
		{ node_id: 'n241', language: 'en', translation: 'I need a doctor' },
		{ node_id: 'n241', language: 'es', translation: 'Necesito un médico' },
		{ node_id: 'n242', language: 'en', translation: 'Call an ambulance' },
		{ node_id: 'n242', language: 'es', translation: 'Llama a una ambulancia' },
		{ node_id: 'n243', language: 'en', translation: 'I have a headache' },
		{ node_id: 'n243', language: 'es', translation: 'Tengo dolor de cabeza' },
		{ node_id: 'n244', language: 'en', translation: 'I feel sick' },
		{ node_id: 'n244', language: 'es', translation: 'Me siento mal' },
		{ node_id: 'n245', language: 'en', translation: 'Where is the hospital?' },
		{ node_id: 'n245', language: 'es', translation: '¿Dónde está el hospital?' },
		{ node_id: 'n246', language: 'en', translation: 'Cat' },
		{ node_id: 'n246', language: 'es', translation: 'Gato' },
		{ node_id: 'n247', language: 'en', translation: 'Dog' },
		{ node_id: 'n247', language: 'es', translation: 'Perro' },
		{ node_id: 'n248', language: 'en', translation: 'Bird' },
		{ node_id: 'n248', language: 'es', translation: 'Pájaro' },
		{ node_id: 'n249', language: 'en', translation: 'Fish' },
		{ node_id: 'n249', language: 'es', translation: 'Pez' },
		{ node_id: 'n250', language: 'en', translation: 'Horse' },
		{ node_id: 'n250', language: 'es', translation: 'Caballo' },
		{ node_id: 'n251', language: 'en', translation: 'Cow' },
		{ node_id: 'n251', language: 'es', translation: 'Vaca' },
		{ node_id: 'n252', language: 'en', translation: 'Sheep' },
		{ node_id: 'n252', language: 'es', translation: 'Oveja' },
		{ node_id: 'n253', language: 'en', translation: 'Pig' },
		{ node_id: 'n253', language: 'es', translation: 'Cerdo' },
		{ node_id: 'n254', language: 'en', translation: 'Chicken' },
		{ node_id: 'n254', language: 'es', translation: 'Gallina' },
		{ node_id: 'n255', language: 'en', translation: 'Rabbit' },
		{ node_id: 'n255', language: 'es', translation: 'Conejo' },
		{ node_id: 'n256', language: 'en', translation: 'Teacher' },
		{ node_id: 'n256', language: 'es', translation: 'Profesor' },
		{ node_id: 'n257', language: 'en', translation: 'Doctor' },
		{ node_id: 'n257', language: 'es', translation: 'Médico' },
		{ node_id: 'n258', language: 'en', translation: 'Engineer' },
		{ node_id: 'n258', language: 'es', translation: 'Ingeniero' },
		{ node_id: 'n259', language: 'en', translation: 'Nurse' },
		{ node_id: 'n259', language: 'es', translation: 'Enfermera' },
		{ node_id: 'n260', language: 'en', translation: 'Lawyer' },
		{ node_id: 'n260', language: 'es', translation: 'Abogado' },
		{ node_id: 'n261', language: 'en', translation: 'Chef' },
		{ node_id: 'n261', language: 'es', translation: 'Cocinero' },
		{ node_id: 'n262', language: 'en', translation: 'Driver' },
		{ node_id: 'n262', language: 'es', translation: 'Conductor' },
		{ node_id: 'n263', language: 'en', translation: 'Artist' },
		{ node_id: 'n263', language: 'es', translation: 'Artista' },
		{ node_id: 'n264', language: 'en', translation: 'Musician' },
		{ node_id: 'n264', language: 'es', translation: 'Músico' },
		{ node_id: 'n265', language: 'en', translation: 'Writer' },
		{ node_id: 'n265', language: 'es', translation: 'Escritor' },
		{ node_id: 'n266', language: 'en', translation: 'Table' },
		{ node_id: 'n266', language: 'es', translation: 'Mesa' },
		{ node_id: 'n267', language: 'en', translation: 'Chair' },
		{ node_id: 'n267', language: 'es', translation: 'Silla' },
		{ node_id: 'n268', language: 'en', translation: 'Bed' },
		{ node_id: 'n268', language: 'es', translation: 'Cama' },
		{ node_id: 'n269', language: 'en', translation: 'Sofa' },
		{ node_id: 'n269', language: 'es', translation: 'Sofá' },
		{ node_id: 'n270', language: 'en', translation: 'Lamp' },
		{ node_id: 'n270', language: 'es', translation: 'Lámpara' },
		{ node_id: 'n271', language: 'en', translation: 'Mirror' },
		{ node_id: 'n271', language: 'es', translation: 'Espejo' },
		{ node_id: 'n272', language: 'en', translation: 'Clock' },
		{ node_id: 'n272', language: 'es', translation: 'Reloj' },
		{ node_id: 'n273', language: 'en', translation: 'Door' },
		{ node_id: 'n273', language: 'es', translation: 'Puerta' },
		{ node_id: 'n274', language: 'en', translation: 'Window' },
		{ node_id: 'n274', language: 'es', translation: 'Ventana' },
		{ node_id: 'n275', language: 'en', translation: 'Television' },
		{ node_id: 'n275', language: 'es', translation: 'Televisión' },
		{ node_id: 'n276', language: 'en', translation: 'Car' },
		{ node_id: 'n276', language: 'es', translation: 'Coche' },
		{ node_id: 'n277', language: 'en', translation: 'Bicycle' },
		{ node_id: 'n277', language: 'es', translation: 'Bicicleta' },
		{ node_id: 'n278', language: 'en', translation: 'Motorcycle' },
		{ node_id: 'n278', language: 'es', translation: 'Motocicleta' },
		{ node_id: 'n279', language: 'en', translation: 'Boat' },
		{ node_id: 'n279', language: 'es', translation: 'Barco' },
		{ node_id: 'n280', language: 'en', translation: 'Airplane' },
		{ node_id: 'n280', language: 'es', translation: 'Avión' },
		{ node_id: 'n281', language: 'en', translation: 'Road' },
		{ node_id: 'n281', language: 'es', translation: 'Carretera' },
		{ node_id: 'n282', language: 'en', translation: 'Bridge' },
		{ node_id: 'n282', language: 'es', translation: 'Puente' },
		{ node_id: 'n283', language: 'en', translation: 'Street' },
		{ node_id: 'n283', language: 'es', translation: 'Calle' },
		{ node_id: 'n284', language: 'en', translation: 'City' },
		{ node_id: 'n284', language: 'es', translation: 'Ciudad' },
		{ node_id: 'n285', language: 'en', translation: 'Village' },
		{ node_id: 'n285', language: 'es', translation: 'Pueblo' },
		{ node_id: 'n286', language: 'en', translation: 'Mountain' },
		{ node_id: 'n286', language: 'es', translation: 'Montaña' },
		{ node_id: 'n287', language: 'en', translation: 'River' },
		{ node_id: 'n287', language: 'es', translation: 'Río' },
		{ node_id: 'n288', language: 'en', translation: 'Lake' },
		{ node_id: 'n288', language: 'es', translation: 'Lago' },
		{ node_id: 'n289', language: 'en', translation: 'Forest' },
		{ node_id: 'n289', language: 'es', translation: 'Bosque' },
		{ node_id: 'n290', language: 'en', translation: 'Beach' },
		{ node_id: 'n290', language: 'es', translation: 'Playa' },
		{ node_id: 'n291', language: 'en', translation: 'Morning' },
		{ node_id: 'n291', language: 'es', translation: 'Mañana' },
		{ node_id: 'n292', language: 'en', translation: 'Afternoon' },
		{ node_id: 'n292', language: 'es', translation: 'Tarde' },
		{ node_id: 'n293', language: 'en', translation: 'Evening' },
		{ node_id: 'n293', language: 'es', translation: 'Noche' },
		{ node_id: 'n294', language: 'en', translation: 'Night' },
		{ node_id: 'n294', language: 'es', translation: 'Noche' },
		{ node_id: 'n295', language: 'en', translation: 'Day' },
		{ node_id: 'n295', language: 'es', translation: 'Día' },
		{ node_id: 'n296', language: 'en', translation: 'Week' },
		{ node_id: 'n296', language: 'es', translation: 'Semana' },
		{ node_id: 'n297', language: 'en', translation: 'Month' },
		{ node_id: 'n297', language: 'es', translation: 'Mes' },
		{ node_id: 'n298', language: 'en', translation: 'Year' },
		{ node_id: 'n298', language: 'es', translation: 'Año' },
		{ node_id: 'n299', language: 'en', translation: 'Hour' },
		{ node_id: 'n299', language: 'es', translation: 'Hora' },
		{ node_id: 'n300', language: 'en', translation: 'Minute' },
		{ node_id: 'n300', language: 'es', translation: 'Minuto' },
		{ node_id: 'n301', language: 'en', translation: 'Yes' },
		{ node_id: 'n301', language: 'es', translation: 'Sí' },
		{ node_id: 'n302', language: 'en', translation: 'No' },
		{ node_id: 'n302', language: 'es', translation: 'No' },
		{ node_id: 'n303', language: 'en', translation: 'Maybe' },
		{ node_id: 'n303', language: 'es', translation: 'Tal vez' },
		{ node_id: 'n304', language: 'en', translation: 'Always' },
		{ node_id: 'n304', language: 'es', translation: 'Siempre' },
		{ node_id: 'n305', language: 'en', translation: 'Never' },
		{ node_id: 'n305', language: 'es', translation: 'Nunca' },
		{ node_id: 'n306', language: 'en', translation: 'Sometimes' },
		{ node_id: 'n306', language: 'es', translation: 'A veces' },
		{ node_id: 'n307', language: 'en', translation: 'Now' },
		{ node_id: 'n307', language: 'es', translation: 'Ahora' },
		{ node_id: 'n308', language: 'en', translation: 'Later' },
		{ node_id: 'n308', language: 'es', translation: 'Más tarde' },
		{ node_id: 'n309', language: 'en', translation: 'Soon' },
		{ node_id: 'n309', language: 'es', translation: 'Pronto' },
		{ node_id: 'n310', language: 'en', translation: 'Yesterday' },
		{ node_id: 'n310', language: 'es', translation: 'Ayer' },
		{ node_id: 'n311', language: 'en', translation: 'Today' },
		{ node_id: 'n311', language: 'es', translation: 'Hoy' },
		{ node_id: 'n312', language: 'en', translation: 'Tomorrow' },
		{ node_id: 'n312', language: 'es', translation: 'Mañana' },
		{ node_id: 'n313', language: 'en', translation: 'Big' },
		{ node_id: 'n313', language: 'es', translation: 'Grande' },
		{ node_id: 'n314', language: 'en', translation: 'Small' },
		{ node_id: 'n314', language: 'es', translation: 'Pequeño' },
		{ node_id: 'n315', language: 'en', translation: 'Long' },
		{ node_id: 'n315', language: 'es', translation: 'Largo' },
		{ node_id: 'n316', language: 'en', translation: 'Short' },
		{ node_id: 'n316', language: 'es', translation: 'Corto' },
		{ node_id: 'n317', language: 'en', translation: 'Tall' },
		{ node_id: 'n317', language: 'es', translation: 'Alto' },
		{ node_id: 'n318', language: 'en', translation: 'Low' },
		{ node_id: 'n318', language: 'es', translation: 'Bajo' },
		{ node_id: 'n319', language: 'en', translation: 'Fast' },
		{ node_id: 'n319', language: 'es', translation: 'Rápido' },
		{ node_id: 'n320', language: 'en', translation: 'Slow' },
		{ node_id: 'n320', language: 'es', translation: 'Lento' },
		{ node_id: 'n321', language: 'en', translation: 'Beautiful' },
		{ node_id: 'n321', language: 'es', translation: 'Hermoso' },
		{ node_id: 'n322', language: 'en', translation: 'Ugly' },
		{ node_id: 'n322', language: 'es', translation: 'Feo' },
		{ node_id: 'n323', language: 'en', translation: 'Good' },
		{ node_id: 'n323', language: 'es', translation: 'Bueno' },
		{ node_id: 'n324', language: 'en', translation: 'Bad' },
		{ node_id: 'n324', language: 'es', translation: 'Malo' },
		{ node_id: 'n325', language: 'en', translation: 'New' },
		{ node_id: 'n325', language: 'es', translation: 'Nuevo' },
		{ node_id: 'n326', language: 'en', translation: 'Old' },
		{ node_id: 'n326', language: 'es', translation: 'Viejo' },
		{ node_id: 'n327', language: 'en', translation: 'I like to read books' },
		{ node_id: 'n327', language: 'es', translation: 'Me gusta leer libros' },
		{ node_id: 'n328', language: 'en', translation: 'She runs every morning' },
		{ node_id: 'n328', language: 'es', translation: 'Ella corre todas las mañanas' },
		{ node_id: 'n329', language: 'en', translation: 'We are going to the park' },
		{ node_id: 'n329', language: 'es', translation: 'Vamos al parque' },
		{ node_id: 'n330', language: 'en', translation: 'They play soccer on weekends' },
		{ node_id: 'n330', language: 'es', translation: 'Ellos juegan fútbol los fines de semana' },
		{ node_id: 'n331', language: 'en', translation: 'He writes music' },
		{ node_id: 'n331', language: 'es', translation: 'Él escribe música' },
		{ node_id: 'n332', language: 'en', translation: 'The cat sleeps on the sofa' },
		{ node_id: 'n332', language: 'es', translation: 'El gato duerme en el sofá' },
		{ node_id: 'n333', language: 'en', translation: 'I need more time' },
		{ node_id: 'n333', language: 'es', translation: 'Necesito más tiempo' },
		{ node_id: 'n334', language: 'en', translation: 'She is very happy today' },
		{ node_id: 'n334', language: 'es', translation: 'Ella está muy feliz hoy' },
		{ node_id: 'n335', language: 'en', translation: 'We live in a small house' },
		{ node_id: 'n335', language: 'es', translation: 'Vivimos en una casa pequeña' },
		{ node_id: 'n336', language: 'en', translation: 'They want to travel' },
		{ node_id: 'n336', language: 'es', translation: 'Ellos quieren viajar' },
		{ node_id: 'n337', language: 'en', translation: 'Book' },
		{ node_id: 'n337', language: 'es', translation: 'Libro' },
		{ node_id: 'n338', language: 'en', translation: 'Pen' },
		{ node_id: 'n338', language: 'es', translation: 'Pluma' },
		{ node_id: 'n339', language: 'en', translation: 'Pencil' },
		{ node_id: 'n339', language: 'es', translation: 'Lápiz' },
		{ node_id: 'n340', language: 'en', translation: 'Paper' },
		{ node_id: 'n340', language: 'es', translation: 'Papel' },
		{ node_id: 'n341', language: 'en', translation: 'Notebook' },
		{ node_id: 'n341', language: 'es', translation: 'Cuaderno' },
		{ node_id: 'n342', language: 'en', translation: 'Bag' },
		{ node_id: 'n342', language: 'es', translation: 'Bolso' },
		{ node_id: 'n343', language: 'en', translation: 'School' },
		{ node_id: 'n343', language: 'es', translation: 'Escuela' },
		{ node_id: 'n344', language: 'en', translation: 'Classroom' },
		{ node_id: 'n344', language: 'es', translation: 'Aula' },
		{ node_id: 'n345', language: 'en', translation: 'Desk' },
		{ node_id: 'n345', language: 'es', translation: 'Escritorio' },
		{ node_id: 'n346', language: 'en', translation: 'Chair' },
		{ node_id: 'n346', language: 'es', translation: 'Silla' },
		{ node_id: 'n347', language: 'en', translation: 'Friend' },
		{ node_id: 'n347', language: 'es', translation: 'Amigo' },
		{ node_id: 'n348', language: 'en', translation: 'Love' },
		{ node_id: 'n348', language: 'es', translation: 'Amor' },
		{ node_id: 'n349', language: 'en', translation: 'Peace' },
		{ node_id: 'n349', language: 'es', translation: 'Paz' },
		{ node_id: 'n350', language: 'en', translation: 'Hope' },
		{ node_id: 'n350', language: 'es', translation: 'Esperanza' },
		{ node_id: 'n351', language: 'en', translation: 'Dream' },
		{ node_id: 'n351', language: 'es', translation: 'Sueño' },
		{ node_id: 'n352', language: 'en', translation: 'Life' },
		{ node_id: 'n352', language: 'es', translation: 'Vida' },
		{ node_id: 'n353', language: 'en', translation: 'Work' },
		{ node_id: 'n353', language: 'es', translation: 'Trabajo' },
		{ node_id: 'n354', language: 'en', translation: 'Home' },
		{ node_id: 'n354', language: 'es', translation: 'Hogar' },
		{ node_id: 'n355', language: 'en', translation: 'Family' },
		{ node_id: 'n355', language: 'es', translation: 'Familia' },
		{ node_id: 'n356', language: 'en', translation: 'Time' },
		{ node_id: 'n356', language: 'es', translation: 'Tiempo' },
		{ node_id: 'n357', language: 'en', translation: 'Money' },
		{ node_id: 'n357', language: 'es', translation: 'Dinero' },
		{ node_id: 'n358', language: 'en', translation: 'Store' },
		{ node_id: 'n358', language: 'es', translation: 'Tienda' },
		{ node_id: 'n359', language: 'en', translation: 'Market' },
		{ node_id: 'n359', language: 'es', translation: 'Mercado' },
		{ node_id: 'n360', language: 'en', translation: 'Restaurant' },
		{ node_id: 'n360', language: 'es', translation: 'Restaurante' },
		{ node_id: 'n361', language: 'en', translation: 'Menu' },
		{ node_id: 'n361', language: 'es', translation: 'Menú' },
		{ node_id: 'n362', language: 'en', translation: 'Waiter' },
		{ node_id: 'n362', language: 'es', translation: 'Camarero' },
		{ node_id: 'n363', language: 'en', translation: 'Bill' },
		{ node_id: 'n363', language: 'es', translation: 'Cuenta' },
		{ node_id: 'n364', language: 'en', translation: 'Tip' },
		{ node_id: 'n364', language: 'es', translation: 'Propina' },
		{ node_id: 'n365', language: 'en', translation: 'Table' },
		{ node_id: 'n365', language: 'es', translation: 'Mesa' },
		{ node_id: 'n366', language: 'en', translation: 'Glass' },
		{ node_id: 'n366', language: 'es', translation: 'Vaso' },
		{ node_id: 'n367', language: 'en', translation: 'Plate' },
		{ node_id: 'n367', language: 'es', translation: 'Plato' },
		{ node_id: 'n368', language: 'en', translation: 'Fork' },
		{ node_id: 'n368', language: 'es', translation: 'Tenedor' },
		{ node_id: 'n369', language: 'en', translation: 'Knife' },
		{ node_id: 'n369', language: 'es', translation: 'Cuchillo' },
		{ node_id: 'n370', language: 'en', translation: 'Spoon' },
		{ node_id: 'n370', language: 'es', translation: 'Cuchara' },
		{ node_id: 'n371', language: 'en', translation: 'Summer' },
		{ node_id: 'n371', language: 'es', translation: 'Verano' },
		{ node_id: 'n372', language: 'en', translation: 'Winter' },
	],
};
